ALTER TABLE "TimeEntry" 
ADD COLUMN IF NOT EXISTS "state" TEXT DEFAULT 'WORKING',
ADD COLUMN IF NOT EXISTS "workAccumSeconds" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "lastStateChangeAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "capMinutes" INTEGER DEFAULT 960,
ADD COLUMN IF NOT EXISTS "flagStatus" TEXT DEFAULT 'NONE',
ADD COLUMN IF NOT EXISTS "overCapAt" TIMESTAMP(3);

